In [1]:
import numpy as np

**Exercise Q1**

Find sqrt, cosine and sin using arrays

In [2]:
p =  np.array([1, 2, 3, 4, 5, 7], dtype="float64")
print(type(p))

<class 'numpy.ndarray'>


In [3]:
np.sin(p)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
        0.6569866 ])

In [4]:
np.cos(p)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.75390225])

In [5]:
np.sqrt(p)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.64575131])

**Exercise Q2**

Extract
[6, 8, 10]
[24, 26, 28]

In [6]:
a = np.arange(36)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [7]:
ab = a.reshape(6, 6)
ab

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [8]:
ab[1:5:3, 0:5:2]

array([[ 6,  8, 10],
       [24, 26, 28]])

# Chapter 1 Assignment
- Create a null array of size 10 but the fifth value which is 1

In [9]:
arr = np.arange(10,20)
arr[4] = 1
arr

array([10, 11, 12, 13,  1, 15, 16, 17, 18, 19])

- Reverse a above created array (first element becomes last)

In [10]:
print(np.flip(arr))

[19 18 17 16 15  1 13 12 11 10]


- Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
a = np.arange(9)
print(a)
b = a.reshape(3,3)
b

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

- Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
c = np.array([1,2,0,0,4,0])
print(c)
d = np.nonzero(c)
print(d)

[1 2 0 0 4 0]
(array([0, 1, 4], dtype=int64),)


- Create a 3x3x3 array with random values

In [13]:
np.random.randint(20, size = (3, 3, 3))

array([[[ 6,  6,  4],
        [15,  7,  2],
        [11,  1, 16]],

       [[15,  0, 12],
        [11,  3,  6],
        [ 0,  7,  0]],

       [[ 9,  7,  4],
        [19, 11,  3],
        [18,  5,  8]]])

- Create a 10x10 array with random values and find the minimum and maximum values

In [14]:
e = np.random.randint(30, size =(10, 10))
print(e)
print(e.max())
print(e.min())

[[24 26  3  6 27 15 26 14  8 20]
 [ 7  2 19  0 25  7 24 15 11  8]
 [25  0 11 14 26 21 20 19 14  0]
 [27  8 25 13  8  3 13 12 11 10]
 [11  0 24 23  6 27  5 11 19  8]
 [20 10 24 25 29 10  6 29  4 14]
 [ 8 17 23  2 10 18 19 26 19 17]
 [25 10 21 21  1 22 20 17 21  1]
 [17 20 23  8 13 16 21 18 24  3]
 [25 21 21  9 10 11  2 13 10 29]]
29
0


- Create a random vector of size 30 and find the mean value

In [15]:
f = np.random.randint(1, 100, 30)
print(f)
print(np.mean(f))

[ 7 17  6 32 20 97 90 55 11 17 49 27  2 42 77 84 33 93 39 79 24 22 54 56
 44 36 18 65 72 62]
44.333333333333336


- Create a 2d array with 1 on the border and 0 inside

In [16]:
g = np.ones((4,4))
print(g)
g[1:3,1:3] = 0
g

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

- Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [17]:
h = np.random.randint(20, size=(5, 3))
i = np.random.randint(20, size=(3, 2))
print(h)
print(i)

[[ 8  8  3]
 [ 7 13  9]
 [ 5  4  0]
 [ 2 12  3]
 [ 5 19  3]]
[[17  9]
 [ 1  9]
 [13  6]]


In [18]:
z = np.matmul(h, i)
z

array([[183, 162],
       [249, 234],
       [ 89,  81],
       [ 85, 144],
       [143, 234]])

In [19]:
result = h@i
result

array([[183, 162],
       [249, 234],
       [ 89,  81],
       [ 85, 144],
       [143, 234]])

- Extract the integer part of a random array

In [20]:
j = np.random.randint(1, 20, 15).reshape(3,5)
j

array([[11, 18,  4, 10,  4],
       [ 8,  2, 17, 15, 18],
       [13,  3, 13, 19,  1]])

In [21]:
condition = np.mod(j, 4)==0
np.extract(condition, j)

array([4, 4, 8])

- Create a 5x5 matrix with row values ranging from 0 to 4

In [22]:
np.random.randint(4, size=(5,5))

array([[2, 1, 2, 1, 0],
       [1, 2, 0, 1, 1],
       [0, 3, 2, 0, 0],
       [1, 2, 2, 3, 1],
       [2, 0, 3, 1, 2]])

- Create a random vector of size 10 and sort it

In [23]:
k = np.random.randint(0,20,10)
k

array([ 0, 14,  3, 13,  7,  5,  4, 16,  0, 19])

In [24]:
np.sort(k)

array([ 0,  0,  3,  4,  5,  7, 13, 14, 16, 19])

- Consider two random array A anb B, check if they are equal

In [25]:
l = np.random.randint(0,20,10)
m = np.random.randint(0,20,10)
print(l)
print(m)
np.array_equal(l,m)

[ 4  8 18 16  8  7  2 16 12 15]
[18 16  5  6  8  3 15  5  3 13]


False

- How to tell if a given 2D array has null columns?

In [26]:
n = np.array([[1,2,3,0],[10,np.NaN ,0 ,13]])
n

array([[ 1.,  2.,  3.,  0.],
       [10., nan,  0., 13.]])

In [27]:
np.isnan(n)

array([[False, False, False, False],
       [False,  True, False, False]])

- Considering a four dimensions array, how to get sum over the last two axis at once?

In [28]:
o = np.arange(72)
o = np.reshape(o, (4,3,2,3))
print(o)
o.ndim

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]

  [[12 13 14]
   [15 16 17]]]


 [[[18 19 20]
   [21 22 23]]

  [[24 25 26]
   [27 28 29]]

  [[30 31 32]
   [33 34 35]]]


 [[[36 37 38]
   [39 40 41]]

  [[42 43 44]
   [45 46 47]]

  [[48 49 50]
   [51 52 53]]]


 [[[54 55 56]
   [57 58 59]]

  [[60 61 62]
   [63 64 65]]

  [[66 67 68]
   [69 70 71]]]]


4

In [29]:
print(o.sum(axis =(-2, -1)))

[[ 15  51  87]
 [123 159 195]
 [231 267 303]
 [339 375 411]]


- Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)

In [30]:
p = np.random.randint(10, size=(5, 5, 3))
q = np.random.randint(10, size=(5,5))
print(p)
print()
print(q)
q = np.expand_dims(q,axis=2)
pq = p*q

[[[8 3 1]
  [7 9 2]
  [6 9 1]
  [2 6 0]
  [3 8 6]]

 [[7 9 7]
  [7 5 9]
  [4 5 5]
  [4 5 6]
  [4 1 2]]

 [[8 4 3]
  [7 2 2]
  [6 9 5]
  [9 1 9]
  [7 2 1]]

 [[8 0 8]
  [5 9 2]
  [1 9 1]
  [6 5 3]
  [0 2 1]]

 [[6 6 8]
  [1 4 6]
  [3 9 9]
  [3 6 0]
  [4 6 9]]]

[[3 5 5 9 6]
 [0 7 2 0 8]
 [7 8 4 3 8]
 [3 4 2 9 8]
 [5 1 5 2 9]]


In [31]:
print(pq)

[[[24  9  3]
  [35 45 10]
  [30 45  5]
  [18 54  0]
  [18 48 36]]

 [[ 0  0  0]
  [49 35 63]
  [ 8 10 10]
  [ 0  0  0]
  [32  8 16]]

 [[56 28 21]
  [56 16 16]
  [24 36 20]
  [27  3 27]
  [56 16  8]]

 [[24  0 24]
  [20 36  8]
  [ 2 18  2]
  [54 45 27]
  [ 0 16  8]]

 [[30 30 40]
  [ 1  4  6]
  [15 45 45]
  [ 6 12  0]
  [36 54 81]]]


- Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [32]:
import numpy as np
M = np.random.rand(10,10)
print(M)
shape = (8,8,3,3) # number of blocks along each axis and size of each block
strides = M.itemsize * np.array([10,1,10,1]) # number of bytes to skip along each axis
blocks = np.lib.stride_tricks.as_strided(M, shape=shape, strides=strides)
print(blocks.shape)

[[0.64037392 0.34809924 0.62419408 0.56152473 0.77866297 0.1557741
  0.21319624 0.14305997 0.87674095 0.44423975]
 [0.55752728 0.54133905 0.58296735 0.89732562 0.8598428  0.01871798
  0.7144529  0.88074384 0.04125118 0.04893518]
 [0.14069406 0.94267996 0.23844561 0.65797099 0.76490549 0.56564741
  0.63749902 0.77247264 0.95269598 0.38827482]
 [0.03275856 0.66378261 0.2997561  0.51279032 0.3634843  0.00771088
  0.26617607 0.20753137 0.2746319  0.40945487]
 [0.91452849 0.55122    0.23785374 0.77430231 0.23932325 0.28954255
  0.27544128 0.93018916 0.91089962 0.79787546]
 [0.07998039 0.57709545 0.34245969 0.47728587 0.64187726 0.70338724
  0.2555712  0.48569955 0.98393252 0.2605138 ]
 [0.54196967 0.75110441 0.84980515 0.29799784 0.00935393 0.74272757
  0.61415559 0.08029075 0.66782181 0.78627337]
 [0.38771549 0.17568109 0.28494538 0.55508132 0.02638193 0.68568725
  0.22112705 0.91325693 0.92624125 0.17419151]
 [0.37838124 0.81870452 0.70943884 0.44100606 0.4914059  0.8648461
  0.6486581  0

- Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [33]:
import numpy as np
A = np.random.randint(20, size=(16,16))
print(A)
print()
B = A.reshape(4 ,4 ,4 ,4 ).sum(axis=(2 ,3 ))
print(B.shape)

[[ 9  3 10 17 14  0  4 18 14  7  7  7  4  0  9 13]
 [10  3  0 19 16 18 16 15 12  1 15  3 12  0  0 18]
 [ 4 10 17  4 19 17  1 17  0 14 10 18  8 16 17 11]
 [19 10 19 18  2  3  0 18  9  8  7 18  7 16 12 16]
 [14 14 14  8 19  2 11 12  6 15  3 19  7  0 12  5]
 [15  9 11 15 19  6 17 16 12 17 18  2 13 17  5 15]
 [ 9 13 16  5  5 14 15 12  6 10  5 18 12 14  6 17]
 [14  1  3 17  7  6  8  5  0 16 12  7 14 13  8  2]
 [ 3 11 18  2 13 14 15  7 17 19  8  8 14 15 12 11]
 [ 8  0 10  3 10  4  3  6  6 17 12 13  2 14  4  7]
 [ 5 11  8  0  4  2 15 13  1 12 12  8 14 15  3  9]
 [17 10 14  9  6  4 17 17  9 16  3 14 10 14  2 12]
 [ 1 13  4  6 18  2 12  2 15 18  7  0  2  6 12  6]
 [ 6  4  5  8  9 19 18 12 15  3  5  4  6  6  9  3]
 [16 18 19  3 10  9 10  8 14 13  2 17 12 18 17 15]
 [ 6 13  4 19  3 14  8 16 15 10 15  6 19  5 12  7]]

(4, 4)
