# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

To get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
#!pip install numpy

You should consider upgrading via the 'c:\users\admin\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

Advantsges of numpy array over lists

1. Numpy is fast and lists are slow. For numpy a value is stored in binary form eg int32 while lists are bult in integer type and consist of size, reference count, object type, object value.
2. Faster to read due to less bytes of memory.
3.Numpy utilizes contiguous memory

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:


In [4]:
my_list = [1,2,3]
my_list
#type(my_list)
#my_list.dtype#--normal lists do not have data type

[1, 2, 3]

Every time we use a numpy functionality we use the np prefix to say whatever comes after that comes from the numpy package.

In [5]:
arr=np.array(my_list)
print(arr)
type(arr) #The nd in the output stands for n (which can be 1,2,3,4,5) dimension


[1 2 3]


numpy.ndarray

In [6]:
arr=np.array([1,2,3,4])
arr.dtype   #arr.dtype #It a short form for data type. Means that every value that we put inside it is of the type int32. 
          #Int stands for integer(whole number) and how many bits is used to represent that number(32 bits)

dtype('int32')

In [7]:
a=np.array([1,2,3,4,5,7],dtype="float64") 
a.dtype
print(a)

[1. 2. 3. 4. 5. 7.]


In [8]:
p=np.array([1,1,1.4])
print(p)
print(type(p))

[1.  1.  1.4]
<class 'numpy.ndarray'>


In [9]:
x=[1,2,3,4,5.0]
x.shape

AttributeError: 'list' object has no attribute 'shape'

In [10]:
f=np.array([[[[1,2,3,6.2]]]])
#f[2]=11
f.shape
f.ndim

4

In [11]:
f.fill(10)
f.shape
f.size
#print(f)
f.ndim#checking the dimension

4

In [12]:
f=np.array([1,2,3,4,5,6.2])
print(f.dtype) #Has floating data number ie fractional numbers
#indexing
f[0]
f[2]=11 #converted to a float cs the array is a float
f.fill(-4)#Replaces everything with 4
print(f.ndim)# returns the number of dimensions
f.shape #shows the number of elements along each dimension
f.size# Returns the number of elements in the array

float64
1


6

**Universal Functions**

**assignment **find sqrt, cosine, sine** using arrays**

In [13]:
np.sin(p) #Computes the sin of every element of f


array([0.84147098, 0.84147098, 0.98544973])

In [6]:
x=[1,2,3,4]
z=(x,[5,6,7])
z

([1, 2, 3, 4], [5, 6, 7])

In [8]:
#extracting from nested list
z[0][1]

2

**Multi-dimensional Arrays**

In [9]:
a=np.array([[1,2,3,4],[10,11 ,12,13]])
a

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [10]:
print(a.shape) # (rows, columns)-Outermost list has inside of it two lists and each of the inner list has 4 elements
print(a.size) #Total number of elements(product of the shape)
print(a.ndim) #length of the shape

(2, 4)
8
2


In [15]:
my_matrix = [[[1,2,3],[4,5,6],[7,8,9]]]
my_matrix

[[[1, 2, 3], [[[4, 5, 6]]], [7, 8, 9]]]

In [16]:
a=np.array(my_matrix)
a.ndim


C:\Users\Admin\AppData\Local\Temp/ipykernel_10608/552348630.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array(my_matrix)


2

In [12]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a.shape
print(a)
print(a.min())#minimum value
print(a.max())#maximum value
print(a.sum()) #Returns sum of all the array elements
print(a.sum(axis=0)) #sum as a column
print(a.sum(axis=1))sum of rows

[[1 2 3 4]
 [5 6 7 8]]
1
8
36
[ 6  8 10 12]
[10 26]


In [55]:
b.sum(axis=0)  #column sum
b.sum(axis=1)  #Rows sum
print(b.mean(axis=0)) #columns mean
print(b.mean(axis=1))  #Rows mean
print(b.mean(axis=None))#mean of whole matrix

[10. 11. 12. 13. 14.]
[ 2.  7. 12. 17. 22.]
12.0


## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [6]:
np.arange(0,26)

array([ 0,  5, 10, 15, 20, 25])

In [26]:
np.arange(0,11,3)# 3 shows the value the sequence will increase by

array([0, 3, 6, 9])

### zeros and ones

Generate arrays of zeros or ones

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
p = np.zeros(5)
p

array([0., 0., 0., 0., 0.])

In [4]:
p.fill(6)
p

array([6., 6., 6., 6., 6.])

In [17]:
np.zeros((5,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [27]:
np.ones(3)

array([ 1.,  1.,  1.])

In [76]:
a=np.ones((3,3,2))
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [5]:
a=np.ones((4,2), dtype="float64") #You can specify the data type
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
a=np.ones((4,2), dtype="int64") #You can specify the data type
a

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

### any other value

In [79]:
a.shape

(4, 2)

In [7]:
b=np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.full_like(b,8)

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [6]:
np.full_like(a,4) #a must be defined

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [81]:
a=np.full(b.shape,9)
a

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

### linspace
Return evenly spaced numbers over a specified interval.

In [10]:
np.linspace(0,10,4) #Three elements between 0 an 10
#generates evenly spaced values

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [11]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [30]:
np.linspace(0,10,50)


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [50]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [91]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.sum(axis=1))

[10 26]


[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
4.0
4.0
36.0
[12. 12. 12.]
[16 16]


## eye or identity

Creates an identity matrix (leading diagonal is one and the rest is zero)

In [13]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.eye(5,4)#identity matrix must be a square matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [21]:
np.eye(2,2)


array([[1., 0.],
       [0., 1.]])

In [22]:
a=np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [26]:
np.random.rand(5)

array([0.19644035, 0.80869192, 0.11176183, 0.38567202, 0.58736256])

In [27]:
np.random.rand(5,5) #creates a matrix of random numbers between 0 and 1

array([[0.20480643, 0.07533072, 0.58112176, 0.11405836, 0.7640704 ],
       [0.74454003, 0.55640771, 0.6393259 , 0.61368598, 0.29261561],
       [0.27811808, 0.12414375, 0.52508399, 0.29040184, 0.07705423],
       [0.76931512, 0.45952208, 0.48094602, 0.56086845, 0.80407271],
       [0.79701733, 0.59385287, 0.64960912, 0.75278912, 0.59898566]])

In [29]:
np.random.random_sample(6)

array([0.51762174, 0.64478939, 0.84594882, 0.2525164 , 0.14492639,
       0.79270179])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [31]:
np.random.randn(200)

array([ 1.73432162e+00, -2.45957589e-01,  1.09790806e+00,  1.01397789e-01,
        8.77378167e-01, -5.92505921e-01, -8.20529165e-02, -6.75494922e-02,
        4.85825628e-01, -1.40620168e-01,  3.42102009e-01, -1.59653046e-01,
       -9.13079186e-03,  6.17324666e-01,  1.45913959e+00,  2.33340270e+00,
        4.36110878e-01, -1.06463679e+00,  1.12191105e-01,  1.21742123e-01,
        9.05410186e-01, -2.41810563e-01, -9.96929993e-01, -7.33059360e-01,
       -1.13608219e+00,  8.50310393e-01,  1.13505423e-01, -8.12555806e-01,
       -2.43571247e-01,  1.19294684e+00, -1.09856356e+00, -8.61093648e-01,
        2.00151649e+00,  5.10852876e-01,  4.50076076e-01, -1.96806948e-01,
        1.17755130e-01,  1.41278044e+00,  6.76396469e-01, -8.44962451e-01,
        8.56464921e-01,  5.34330652e-01, -9.64412558e-01,  1.73267340e-01,
        7.46795870e-01,  1.22694087e+00,  8.15645574e-01, -1.94144379e-01,
        1.13356370e+00, -4.58165623e-01, -2.85570649e-01, -4.43987742e-01,
        1.50956414e+00, -

In [19]:
np.random.randn(5,5)

array([[ 0.63299963, -0.06515444,  0.49750358,  0.77288684, -0.02693147],
       [-0.4542713 ,  0.0295765 ,  1.24897868,  0.35972798,  0.36226007],
       [-1.33599688,  0.13959165, -3.6250092 ,  1.72810543, -1.90042346],
       [-0.0759669 ,  0.70582982, -0.20547447, -1.19612171,  0.1607388 ],
       [-1.75663058, -0.59298069, -0.41636971, -0.03868956,  0.9767362 ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [27]:
np.random.randint(1,100,3 )

array([53, 51, 93])

In [101]:
np.random.randint(1,100,10)

array([61, 22, 13, 49, 79, 68, 90, 52, 50, 72])

In [68]:
np.random.randint(7, size=(3,3)) #Starts from zero without start value.

array([[6, 4, 6],
       [0, 2, 4],
       [1, 5, 4]])

In [69]:
np.random.randint(4,7, size=(3,3)) #Assigns random number from 4 to 7 on a 3 by 3 array and 7 is not included

array([[6, 5, 6],
       [5, 6, 4],
       [4, 6, 5]])

ranarr = np.random.randint(0,50,10)
print(ranarr## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [40]:
ranarr = np.random.randint(0,50,10)
print(ranarr)

[ 7 46 26 11 44  9 18  2 21  8]


In [33]:
arr = np.arange(25) #Prints one dimension array
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr

array([ 7, 46, 26, 11, 44,  9, 18,  2, 21,  8])

## Reshape
Returns an array containing the same data with a new shape.

In [37]:
b=arr.reshape(5,5) #number has to fit in matrix
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape)
a.reshape(4,2)
print(a.reshape(4,2))
#a.ndim

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### max,min,argmax,argmin, sum,sqrt

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [47]:
ranarr

array([ 7, 46, 26, 11, 44,  9, 18,  2, 21,  8])

In [48]:
ranarr.max()

46

In [49]:
ranarr.argmax()  #Gives the location of the maximum value

1

In [50]:
ranarr.min()

2

In [51]:
ranarr.argmin() #Gives the location of the minimum values

7

In [52]:
ranarr.sum()

192

In [53]:
np.sqrt(ranarr)  #Returns square root of all the elements

array([2.64575131, 6.78232998, 5.09901951, 3.31662479, 6.63324958,
       3.        , 4.24264069, 1.41421356, 4.58257569, 2.82842712])

b.sum(axis=0)  #column sum
b.sum(axis=1)  #Rows sum
print(b.mean(axis=0)) #columns mean
print(b.mean(axis=1))  #Rows mean
print(b.mean(axis=None))

### Broadcasting

In [56]:
y=[1,2,3,4,5]
x=[[1,2,3,4],[4,5,6,7]]
c=y+x
c



[1, 2, 3, 4, 5, [1, 2, 3, 4], [4, 5, 6, 7]]

In [57]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [64]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,1,9])
print(a)
print()
print(b)
print()
print(a.shape)
print(b.shape)
print()
c=a+b     #We dont need to have array of the same dimension and shape
print(b.ndim)
print()
#print(a.shape)

#print(b.shape)

print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 1 9]

(3, 3)
(3,)

1

(3, 3)
[[ 2  3 12]
 [ 5  6 15]
 [ 8  9 18]]


## Shape

Shape is an attribute that arrays have (not a method):

In [38]:
# Vector
arr = np.arange(25)
arr.shape
arr.ndim
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
# Notice the two sets of brackets
arr2=arr.reshape(1,25)
arr2.ndim
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
arr.reshape(1,25).shape

(1, 25)

In [70]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [76]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [75]:
arr.dtype

dtype('int64')

### Concatenate

In [67]:
a=np.array([[1,2], [4,5]])
b=np.array([[7,8]])
c=np.concatenate((a,b))
c
#a.ndim
#b.ndim

array([[1, 2],
       [4, 5],
       [7, 8]])

**Numpy.ravel()** 

It converts the entire array into a single row

In [69]:
c.ravel()

array([1, 2, 4, 5, 7, 8])

### Array slicing

In [70]:
a=np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [71]:
a=np.arange(36)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [72]:
ab=a.reshape(6,6)
ab

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [73]:
#extracting all rows
ab[:,]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

**Assignment**
extract 

6 8 10 

24 26 28

In [76]:
#extracting colums
ab[:,0:5:2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [77]:
ab[1:5:3,0:5:2]

array([[ 6,  8, 10],
       [24, 26, 28]])

In [74]:
ab[0:4:3,0:5:2]

array([[ 0,  2,  4],
       [30, 32, 34]])

In [75]:
ab[0:6:5,]

array([[ 0,  1,  2,  3,  4,  5],
       [50, 51, 52, 53, 54, 55]])

In [81]:
ab[3:6:2,1:6:2]

array([[31, 33, 35],
       [51, 53, 55]])

In [77]:
ab[0:6:5,0:3:1]

array([[ 0,  1,  2],
       [50, 51, 52]])

In [97]:
a[4:,] #Row four and all the columns
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [103]:
a[0,3::2] #To extract element 3 and five in row 1(2 denotes a jump of two)

array([3, 5])

In [98]:
a[:, 4] #extracting column 5

array([ 4, 14, 24, 34, 44, 54])

In [99]:
a[2,2]

22

In [100]:
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [104]:
a[:,1::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25],
       [31, 33, 35],
       [41, 43, 45],
       [51, 53, 55]])

# Chapter 1 Assignment
1. Create a null array of size 10 but the fifth value which is 1
2. Reverse a above created array (first element becomes last)
3. Create a 3x3 matrix with values ranging from 0 to 8
4. Find indices of non-zero elements from [1,2,0,0,4,0]
5. Create a 3x3x3 array with random values
6. Create a 10x10 array with random values and find the minimum and maximum values
7. Create a random vector of size 30 and find the mean value
8. Create a 2d array with 1 on the border and 0 inside
9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
10. Extract the integer part of a random array
11. Create a 5x5 matrix with row values ranging from 0 to 4
12. Create a random vector of size 10 and sort it
13. Consider two random array A anb B, check if they are equal
14. How to tell if a given 2D array has null columns?
15. Considering a four dimensions array, how to get sum over the last two axis at once?
16. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
17. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
18. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?