In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]
print(my_list)
print(type(my_list))

[1, 2, 3]
<class 'list'>


In [3]:
arr1 = np.array(my_list)
print(arr1)
print(type(arr1))
arr1.dtype

[1 2 3]
<class 'numpy.ndarray'>


dtype('int32')

In [4]:
#we can do conversions
a = np.array([1, 2, 3, 4, 5, 7], dtype="float64")
print(a.dtype)
print(a)

float64
[1. 2. 3. 4. 5. 7.]


In [5]:
#when you have int and float - converts all to float
p = np.array([1, 1, 1.4])
print(p)
print(p.dtype)
print(type(p))

[1.  1.  1.4]
float64
<class 'numpy.ndarray'>


# Heading
## Heading

- **to make bold**
- <u>to underline<u/>
- <i>to italics<i/>
- _italics also_
- ~strike through~
- <del>strike through also<del>
- `highlight`

In [7]:
#list cant give shape
x=[1,2,3,4,5.0]
x.shape()

AttributeError: 'list' object has no attribute 'shape'

In [8]:
#extarct data
f=np.array([[[1,2,3,6.2]]])
#f[2]=0
f
f.shape
#f.size
#f.ndim #number of square brackets

(1, 1, 4)

In [9]:
f=np.array([[[1,2,3,6.2]]])
#f[2]=0
f
f.shape #brackests

(1, 1, 4)

# BUILT IN METHODS

In [10]:
#generate arrays
import numpy as np

In [11]:
#use arrange function
np.arange(0, 26)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [12]:
np.arange(0, 200, 2)#start, end and spacing]

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])